### ISSUE TITLE
Sound Hard with ABC

### ISSUE THREAD

**Issue by Ehaw04** [pescap/ScattPINNs#11]
To do:

- [ ] Validate [script]
- [ ] Validate [unit tests](https://github.com/pescap/ScattPINNs/actions) for the script
- [ ] Validate the [doc]

**Comment by pescap** [comment]
This is the next step @Ehaw04

**Comment by Ehaw04** [comment]
I’ll assume I need to keep using the same pde (Helmholtz equation). Does this case have an “f” term? Is it like https://github.com/pescap/ScattPINNs/blob/0eeb1dbbd6557a3f6559d9f677c51a9bad428bad/dev/waves-deepxde/SoundHardABC.ipynb?

**Comment by pescap** [comment]
Yes, it has no source term. See Equation (1.2) in:
https://arxiv.org/pdf/2101.02154.pdf
