### ISSUE TITLE
Neumann Complex with coskx

### ISSUE THREAD

**Issue by pescap** [pescap/ScattPINNs#7]
Case:
- Helmholtz problem for a 2D square with Neumann null boundary conditions.
- Set `f= k^2 * [cos(kx),cos(kx)]`. The analytic solution is `u = [cos(kx), cos(kx)]`.

To do: 

- [x] Validate [script](https://github.com/pescap/ScattPINNs/blob/main/examples/forward/Helmholtz_Neumann_2d_complex_coskx.py) 
- [x] Validate [unit tests](https://github.com/pescap/ScattPINNs/actions) for the script 
- [ ] Validate the [doc](https://github.com/pescap/ScattPINNs/blob/main/docs/source/forward/helmholtz.2d.neumann.complex.coskx.rst) for the script.

**Comment by Ehaw04** [comment]
@ArtemioA Could you finish the doc for this?
