### ISSUE TITLE
Neumann complex with eikx

### ISSUE THREAD

**Issue by pescap** [pescap/ScattPINNs#8]
Case:

Helmholtz problem for a 2D square with Neumann non null boundary conditions.
Set f= k^2 * [cos(kx),sin(kx)]. The analytic solution is u = [cos(kx), sin(kx)].
To do:

- [ ] Validate [script](https://github.com/pescap/ScattPINNs/blob/main/examples/forward/Helmholtz_Neumann_2d_complex_coskx.py)
- [ ] Validate [unit tests](https://github.com/pescap/ScattPINNs/actions) for the script
- [ ] Validate the [doc](https://github.com/pescap/ScattPINNs/blob/main/docs/source/forward/helmholtz.2d.neumann.complex.coskx.rst) for the script.

Help: Check the scripts with `eikx` in [dev](https://github.com/pescap/ScattPINNs/tree/main/dev/waves-deepxde)

**Comment by Ehaw04** [comment]
@ArtemioA  Could you finish the doc for this?

**Comment by artemioadaysolvers** [comment]
![image](https://user-images.githubusercontent.com/78178128/172934016-04af135c-1ff8-45e9-82e6-080ef8156dc7.png)
![image](https://user-images.githubusercontent.com/78178128/172934099-6cf035cb-2221-4040-b16d-7e162319fe70.png)
